"""empty message

Revision ID: 11379aa802ab
Revises: 
Create Date: 2025-04-19 17:39:04.584009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11379aa802ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', name='chattype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator_uuid'], ['users.user_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('sender_uuid', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_status', sa.Enum('READ', 'UNREAD', name='read_status'), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chats',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uuid', 'chat')
    )
    op.create_table('message_user_read',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('message', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READ', 'UNREAD', name='read_status'), nullable=False),
    sa.ForeignKeyConstraint(['message'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_user_read')
    op.drop_table('user_chats')
    op.drop_table('messages')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
