"""empty message

Revision ID: 2e52e8625aeb
Revises: ddd0012f876a
Create Date: 2025-04-12 17:29:41.044346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e52e8625aeb'
down_revision: Union[str, None] = 'ddd0012f876a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', name='chattype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('sender', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_status', sa.Enum('READ', 'UNREAD', name='read_status'), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chats',
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user', 'chat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chats')
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
