"""empty message

Revision ID: 46dfa3e04884
Revises: cceaf997c3b0
Create Date: 2025-04-26 10:54:09.418778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46dfa3e04884'
down_revision: Union[str, None] = 'cceaf997c3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_index('ix_messages_chat', table_name='messages')
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.drop_constraint('messages_chat_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'chat')
    op.add_column('user_chats', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_chats_chat_fkey', 'user_chats', type_='foreignkey')
    op.create_foreign_key(None, 'user_chats', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_chats', 'chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('chat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_chats', type_='foreignkey')
    op.create_foreign_key('user_chats_chat_fkey', 'user_chats', 'chats', ['chat'], ['id'], ondelete='CASCADE')
    op.drop_column('user_chats', 'chat_id')
    op.add_column('messages', sa.Column('chat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_fkey', 'messages', 'chats', ['chat'], ['id'])
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.create_index('ix_messages_chat', 'messages', ['chat'], unique=False)
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###
