"""empty message

Revision ID: 81dbd89ce632
Revises: dfe863506398
Create Date: 2025-04-11 20:21:07.038164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81dbd89ce632'
down_revision: Union[str, None] = 'dfe863506398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_chats',
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user', 'chat')
    )
    op.drop_table('groups')
    op.add_column('chats', sa.Column('creator', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['creator'], ['uuid'], ondelete='CASCADE')
    op.drop_column('chats', 'type')
    op.add_column('messages', sa.Column('chat', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('sender', sa.UUID(), nullable=False))
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender'], ['uuid'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat'], ['id'])
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'chat')
    op.add_column('chats', sa.Column('type', postgresql.ENUM('PRIVATE', 'GROUP', name='chat_type'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'creator')
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participants', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    op.drop_table('user_chats')
    op.drop_table('users')
    # ### end Alembic commands ###
