"""empty message

Revision ID: a8160c7b8f4e
Revises: fb7e08400c5f
Create Date: 2025-04-15 17:01:28.695721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8160c7b8f4e'
down_revision: Union[str, None] = 'fb7e08400c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_user_read', sa.Column('status', sa.Enum('READ', 'UNREAD', name='read_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_user_read', 'status')
    # ### end Alembic commands ###
