"""empty message

Revision ID: cceaf997c3b0
Revises: 11379aa802ab
Create Date: 2025-04-25 18:01:17.920174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cceaf997c3b0'
down_revision: Union[str, None] = '11379aa802ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_user_read_message'), 'message_user_read', ['message'], unique=False)
    op.create_index(op.f('ix_messages_chat'), 'messages', ['chat'], unique=False)
    op.create_index(op.f('ix_user_chats_user_uuid'), 'user_chats', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chats_user_uuid'), table_name='user_chats')
    op.drop_index(op.f('ix_messages_chat'), table_name='messages')
    op.drop_index(op.f('ix_message_user_read_message'), table_name='message_user_read')
    # ### end Alembic commands ###
