"""empty message

Revision ID: ddd0012f876a
Revises: a8bd41c80e09
Create Date: 2025-04-12 14:52:06.133052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd0012f876a'
down_revision: Union[str, None] = 'a8bd41c80e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', name='chattype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'messages', 'chats', ['chat'], ['id'])
    op.create_foreign_key(None, 'user_chats', 'chats', ['chat'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chats', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_table('chats')
    # ### end Alembic commands ###
