"""empty message

Revision ID: fb7e08400c5f
Revises: 2e52e8625aeb
Create Date: 2025-04-14 21:03:01.773332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7e08400c5f'
down_revision: Union[str, None] = '2e52e8625aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_user_read',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.drop_column('messages', 'read_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read_status', postgresql.ENUM('READ', 'UNREAD', name='read_status'), autoincrement=False, nullable=False))
    op.drop_table('message_user_read')
    # ### end Alembic commands ###
